# Basic Site Settings
locale                   : "en-US"
site_theme               : "default"
title                    : "Stephanie H. Stack"
title_separator          : "-"
name                     : &name "Stephanie H. Stack"
description              : &description "Marine mammalogist specialising in humpback whale ecology, energetics, and conservation"
url                      : https://stephaniestack.github.io
baseurl                  : ""
repository               : "stephaniestack/stephaniestack.github.io"

# Site Author
author:
  avatar           : "profile.png"
  name             : "Stephanie H. Stack"
  pronouns         : "she/her"
  bio              : "Marine mammalogist | Humpback whale behavioural ecology & energetics | UAV photogrammetry | Conservation science"
  location         : "Queensland, Australia"
  employer         : "Griffith University"
  uri              : "https://saltwaterscience.org"
  email            : "stephanie@saltwaterscience.org"

  # Academic websites
  googlescholar    : "https://scholar.google.com/citations?user=pSA-V4UAAAAJ&hl=en"
  orcid            : "https://orcid.org/0000-0002-7199-8408"
  researchgate     : # Add your ResearchGate URL

  # Repositories and software development
  github           : "stephaniestack"

  # Social media
  bluesky          : # Add your Bluesky handle if applicable
  twitter          : # Add your X/Twitter handle if applicable
  instagram        : # Add if applicable

# Publication Categories
